name: mnm
description: 'description'
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  grpc: ^4.1.0
  protobuf: ^4.1.0
  drift: ^2.28.2
  path: ^1.9.1
  http: ^1.5.0
  signals: ^6.0.0
  logging: ^1.2.0

dev_dependencies:
  build_runner: ^2.8.0
  drift_dev: ^2.28.3